# fly.toml app configuration file generated for platform on 2023-11-14T18:52:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "platform"
primary_region = "mad"

[env]
  GOOGLE_REDIRECT_URI="https://platform.fly.dev/auth/callback/google"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
