export { Editor } from '@tiptap/core'
export * from '@tiptap/starter-kit'
export * from '@tiptap/extension-bubble-menu'
export * from '@tiptap/extension-character-count'
export * from '@tiptap/extension-color'
export * from '@tiptap/extension-document'
export * from '@tiptap/extension-dropcursor'
export * from '@tiptap/extension-floating-menu'
export * from '@tiptap/extension-highlight'
export * from '@tiptap/extension-horizontal-rule'
export * from '@tiptap/extension-image'
export * from '@tiptap/extension-link'
export * from '@tiptap/extension-placeholder'
export * from '@tiptap/extension-task-item'
export * from '@tiptap/extension-task-list'
export * from '@tiptap/extension-text-align'
export * from '@tiptap/extension-text-style'
export * from '@tiptap/extension-underline'